In [ ]:
shared_data=['hello, my name']

class ModuleA:
    def add_data(self, data):
        global shared_data
        shared_data.append(data)

class ModuleB:
    def print_data(self):
        global shared_data
        print(shared_data)

module_a=ModuleA()
module_a.add_data(data="Hello")

module_b=ModuleB()
module_b.print_data()

In [ ]:
class DataBase:
    def __init__ (self):
        self._connection = "DB connection"

class UserManager:
    def __init__(self, db):
        self.db=db
    
    def manipulate_db(self):
        self.db._connection = "Hacked connection"

db= DataBase()
print(db._connection)

manager = UserManager(db)
print(manager.db._connection)

manager.manipulate_db()
print(manager.db._connection)
print(db._connection)


In [ ]:
class DataBase:
    def __init__ (self):
        self.__connection = "DB connection"

    def get_connection(self):
        return self.__connection

    def set_connection(self,new_connection):
        if new_connection == "new connection":
             self.__connection = new_connection
        else:
            print("Invalid")

    
class UserManager:
    def __init__(self, db):
        self.db=db
    
    def manipulate_db(self):
        self.db.__connection = "Hacked connection"


db= DataBase()
#print(db._connection)
print(db.get_connection())
print(db.set_connection("new connection"))


manager = UserManager(db)
print(manager.db.get_connection())

manager.manipulate_db()
print(manager.db.get_connection())
print(db.get_connection())




In [ ]:
class Example:
    def __init__(self, value):
        self.value = value

    def show_value(self):
        return self.value

obj = Example(10)
method = obj.show_value
print(method())  # 10 출력


In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

# 인스턴스 생성
person1 = Person("Alice", 30)

# 속성 값 출력
print(person1.name)  # 출력: Alice
print(person1.age)   # 출력: 30


In [ ]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def greet(self):
        return f"Hello, my name is {self.name} and I am {self.age} years old."

# 인스턴스 생성
person1 = Person("Alice", 30)

# 바운드 메서드 출력
print(person1.greet)  # 바운드 메서드 객체 출력
print(person1.greet())  # 메서드 호출 후 결과 출력


In [ ]:
class Student:
    def __init__(self,name):
        self.name=name
        self.professor=None

class Professor :
    def __init__(self,name):
        self.name=name
        self.student = None

    def assign_student(self,student):
        self.student = student
        student.professor = self


student = Student("Alice") #student 객체생성
print(student.professor)
print(student.name)
print('--------------------------')
professor = Professor("Dr.Smith")
print(professor.name)
print(professor.student)
print('--------------------------')
professor.assign_student(student)
print('--------------------------')
print(student.professor.name) #<__main__.Professor object at 0x000001A59F9B2510>
print(student.name) #Alice
print('--------------------------')
print(professor.name) #Dr.Smith
print(professor.student) #<__main__.Student object at 0x000001A59F9B2CC0>

print('-------------------------')


#왜 student.professor에 assign_student을 하면 결과값 출력이 아니라 <__main__.Professor object at 0x000001A59F9B2510>으로 뜨는 거야?

In [ ]:
id(professor.student)

In [ ]:
"""
professor = Professor("Dr.Smith")


professor.assign_student(student)

print(f'{student.name}\'s professor is {student.professor.name}.')
print(f'{professor.name}\'s student is {professor.student.name}.')
"""

In [ ]:
raise Exception('예외 발생')

In [ ]:
def get_ans(ans):
    if ans in ['yes','no']:
        print ('정상적인 입력입니다.')
        if ans =='yes':
            return (ans)
        else :
            return (ans)
    else:
        raise NotImplementedError

In [ ]:
user_input='예'
print(get_ans(user_input))


In [ ]:
while True:
    try :
        ans = input('yes/no 중 하나 입력:>')
        get_ans(ans)
        break
    except Exception as e:
        print('error:',e)    

In [ ]:
f= open('hello.txt','w')
f.write('Hello world!')
f.close()

In [ ]:
f=open('hello.txt','r')
f.read()

In [ ]:
f.close()

In [ ]:
f= open('hello.txt','w')
for _ in range(5):
    n = input('정수:>')
    f.write(n)
    f.write('\n')
f.close()





In [ ]:
with open ('hello.txt','w') as f :
    f.write('hello world~')

In [ ]:
import urllib.request
with urllib.request.urlopen('https://python.org/') as r:
    html = r.read()
    print(html)

In [ ]:
class Cat:
    def __init__(self, name, color):
        self.name= name
        self.color= color

    def meow (self):
        print(f'내 이름은 {self.name}, 색깔은 {self.color}')

nabi=Cat("nabi","black")
nabi.meow()

In [ ]:
class Cat:
    def __init__(self, name, color):
        self.name= name
        self.color= color

    def meow (self):
        print(f'내 이름은 {self.name}, 색깔은 {self.color}')

nabi=Cat("nabi","black")
nabi.meow()

In [ ]:
class Cat:
    def __init__(self, name, color):
        self.name = name
        self.color = color

    def __str__(self):  # self 생략 -> 오류 발생
        return f'내 이름은 {self.name}, 색깔은 {self.color}'

nabi = Cat("nabi", "black")

print(nabi) # 출력문 : 내 이름은 nabi, 색깔은 black


In [ ]:
class Case:
    def __init__(self, brand, model):
        self.brand=brand
        self.model=model
        
    def __str__(self):
        return f'Case(Brand:{self.brand}, Model: {self.model})'
    

class Monitor:
    def __init__(self,brand, size):
        self. brand = brand
        self. size = size

    def __str__(self):
        return f'Monitor(Brand:{self.brand}, Size: {self.size} inches)'
    
class Keyboard:
    def __init__(self, brand, is_mechanical):
        self.brand= brand
        self.is_mechanical=is_mechanical

    def __str__(self):
        return f'Keyboard(Brand:{self.brand}, Mechanical: {self.is_mechanical})'
    
class Computer:
    def __init__(self, case, monitor, keyboard,graphiccard):
        self.case = case
        self.monitor = monitor
        self.keyboard= keyboard
        self.graphiccard = graphiccard

    def __str__(self):
        return (f'Computer\n'
                f'{self.case}\n'
                f'{self.monitor}\n'
                f'{self.keyboard}\n'
                f'{self.graphiccard}')

class GraphicCard:
    def __init__ (self, brand, model):
        self.brand = brand
        self.model = model

    def __str__(self):
        return f'Graphic Card (Brand:{self.brand}, Model : {self.model})'

case = Case("Cooler Master","H50")
monitor = Monitor("Dell",27)
keyboard = Keyboard("Logitech",True)
keyboard1= Keyboard("Happy Hakcing",True)
graphiccard=GraphicCard("NVDEIA","BI2233")

computer = Computer(case,monitor,keyboard,graphiccard)

print(computer)
print(Computer.__str__)


In [ ]:
class Case:
    def __init__(self, brand, model):
        self.brand=brand
        self.model=model
        
    def __str__(self):
        return f'Case(Brand:{self.brand}, Model: {self.model})'
    

class Monitor:
    def __init__(self,brand, size):
        self. brand = brand
        self. size = size

    def __str__(self):
        return f'Monitor(Brand:{self.brand}, Size: {self.size} inches)'
    
class Keyboard:
    def __init__(self, brand, is_mechanical):
        self.brand= brand
        self.is_mechanical=is_mechanical

    def __str__(self):
        return f'Keyboard(Brand:{self.brand}, Mechanical: {self.is_mechanical})'
    
class Labtop:
    def __init__(self, brand):
        self.case = Case(brand,"Zenbook Pro")
        self.monitor = Monitor (brand, 15.6)
        self.keyboard= Keyboard(brand, True)


    def __str__(self):
        return (f'Computer\n'
                f'{self.case}\n'
                f'{self.monitor}\n'
                f'{self.keyboard}\n')


#case = Case("Cooler Master","H50")
#monitor = Monitor("Dell",27)
#keyboard = Keyboard("Logitech",True)

laptop = Labtop("AUS")

case= Case(laptop.case,model='AUS')
print(case)


In [ ]:
class Person:
    def __init__ (self, name):
        self.name = name

    def get_name(self):
        return self.name
    

class PI(Person) :
    def __init__(self, name, position):
        super().__init__(name)
        self.position= position

    def into(self):
        return f'관리직 : {self.get_name()}, 직책 : {self.position}'
    
class Employee(Person):
    def __init__ (self, name, salary=100):
        super().__init__( name)
        self.salary= salary
    def get_salary (self):
        return f'종업원 : {self.get_name()}, 급여:{self.salary}'


In [ ]:
cto = PI('박동민','최고 기술책임자 (CTO)')
worker1= Employee('박동윤',320)
worker2 =Employee('구성순')

print(cto.into())

In [ ]:
print(worker1.get_salary())
print(worker2.get_salary())


In [ ]:
class Person:
    def __init__(self, name,record,grade):
        self.name = name
        self.record = record
        self.grade = grade

    def get_grade (self):
        if self.grade >=70 :
            return '합격입니다.'
        else :
            return '불합격' 

class Student (Person):
    def __init__(self,name,record, grade):
        super().__init__(name,record, grade)

    def info(self):
        return (f' 학생이름 : {self.name}\n'
                f' 학번 : {self.record}\n'
                f' 성적 : {self.grade}\n'
                f' 합격 여부 : {self.get_grade()}\n')
    

name = input('학생 이름 입력')
Student_ID= input('학번입력:')
score= int(input('성적입력:'))
student1 = Student(name,Student_ID,score)

print(student1.info())



In [ ]:
isinstance(student1,Person)

In [ ]:
class Car :
    def __init__ (self,model):
        self.model= model

    def get_model(self):
        return self.model

class Driver :
    def drive(self):
        car= Car("BMW")
        print(f'Driving {car.get_model()}')



driver = Driver()
driver.drive()

In [16]:
class Car :
    def __init__ (self,model):
        self.model= model
    
    def get_model(self):
        return self.model
    
class Driver :
    def create_car(self, model):
        return Car(model)
    
driver = Driver()
car = driver.create_car("BMW")
print(f'Driving {car.get_model()}')

Driving BMW


In [ ]:
from abc import ABC, abstractmethod

class Vehicle (ABC):
    def getOn(self):
        print ("getting on the vehicle")

    def getOff(self):
        print ("Getting off the vehicle")
    

class Transferable(ABC):
    @abstractmethod
    def transfer(self):
        pass

class Bus(Vehicle, Transferable): #Transferable을 상속받음
    def transfer (self):
        print ("Transfered to another subway or bus")

class Subway(Vehicle,Transferable):
    def transfer (self):
        print ("Transfered to another subway or bus")
    
class Taxi (Vehicle):
    pass

#if __name__=="__main__":
    bus = Bus()
    subway = Subway()
    taxi = Taxi()

    bus.getOn()
    subway.getOn()
    taxi.getOn()

    bus.getOff()
    subway.getOff()
    taxi.getOff()

    bus.transfer()
    subway.transfer()

else :
    print('다른 모듈에서 호출했음')

getting on the vehicle
getting on the vehicle
getting on the vehicle
Getting off the vehicle
Getting off the vehicle
Getting off the vehicle
Transfered to another subway or bus
Transfered to another subway or bus


In [26]:
import main_name_cal

print(main_name_cal)

다른 모듈에서 호출했음
<module 'main_name_cal' from 'c:\\src_green\\src\\FirstPython\\PYTHON\\main_name_cal.py'>


In [32]:
class VideoPlayer:
    def __init__(self, format_type):
        self.format_type = format_type

    def start(self):
        if self.format_type == 'MP4':
            self.play_mp4()
        elif self.format_type == 'WMV':
            self.play_WMV()
        elif self.format_type == 'AVI':
            self.play_AVI()
        elif self.format_type == 'MP21':
            self.play_mp21()
        else :
            print('지원하지 않는 방식')
    
    def play_mp4 (self):
        print(' MP4 재생 중 . . . ')
    def play_WMV (self):
        print(' WMV 재생 중 . . . ')
    def play_AVI (self):
        print(' AVI 재생 중 . . . ')
    def play_mp21 (self):
        print(' MP21재생 중 . . . ')


if __name__ == '__main__':
    player = VideoPlayer ("MP4")
    player.start()
    player = VideoPlayer ("WMV")
    player.start()
    player = VideoPlayer ("AVI")
    player.start()
    player = VideoPlayer ("MP21")
    player.start()

 MP4 재생 중 . . . 
 WMV 재생 중 . . . 
 AVI 재생 중 . . . 
 MP21재생 중 . . . 


In [1]:
from abc import ABC , abstractmethod

class PlayStart:
    @abstractmethod
    def start(self):
        pass

class MP4(PlayStart):
    def start (self):
        print(' MP4 재생 중 . . . ')

class WMV(PlayStart) :
    def start(self):
        print(' WMV 재생 중 . . . ')

class AVI(PlayStart) :
    def start(self):
        print(' AVI 재생 중 . . . ')

class MP21(PlayStart) :
    def start(self):
        print(' MP21 재생 중 . . . ')





In [ ]:
class Lecture :
    
    def __init__ (self):
        self.lecturer = "일반강사"
        self.charge = 9000
        

    def display_info(self):
        print(self.lecturer)
        print(f'강사료: {self.charge}원\n')

class LectureNight(Lecture):
    def __init__(self):
        super().__init__()
        self.lecturer = '야간강사'

    def display_info_night(self):
        print(self.lecturer)
        print(f'강사료 : {self.charge * 1.5}원\n')


class LecturerAtGS(Lecture):
    def __init__(self):
        super().__init__()
        self.lecturer = '대학원 강사'

    def display_info(self):
        print(self.lecturer)
        print(f'강사료 : {self.charge *2}원\n')


class LectureWiithWork(Lecture):
    def __init__(self):
        super().__init__()
        self.lecturer='직업이 있는 강사'

    def display_info(self):
        print(self.lecturer)
        print(f'일일 주차비 : {self.charge *0.5}원\n')


if __name__ == "__main__":
    lect = Lecture()
    lect.display_info()

    lect01 = LecturerAtGS()
    lect01.display_info()

    lect02 = LectureNight()
    lect02.display_info()

    lect03 = LectureWiithWork()
    lect03.display_info()


일반강사
강사료: 9000원

대학원 강사
강사료 : 18000원

야간강사
강사료: 9000원

직업이 있는 강사
일일 주차비 : 4500.0원



In [32]:
from abc import ABC, abstractmethod

class Lecturer (ABC):

    def __init__(self):
        self.lecturer = ""
        self.charge= 9000

    @abstractmethod
    def display_info(self):
        pass

class GeneralLecturer(Lecturer):
    def __init__(self):
        super().__init__()
        self.lecturer = '일반 강사'

    def display_info(self):
        print (self.lecturer)
        print(f'강사료 : {self.charge}원 \n')

class LecturerNight(Lecturer):
    def __init__(self):
        super().__init__()
        self.lecturer = '야간 강사'
    
    def display_info(self):
        print (self.lecturer)
        print(f'강사료 : {self.charge* 1.5}원 \n')

class LecturerAtGS(Lecturer):
    def __init__(self):
        super().__init__()
        self.lecturer = '대학원 강사'

    def  display_info(self):
        print(self.lecturer)
        print(f'강사료 : {self.charge *2}원 \n')

class LectureWithWork (Lecturer):
    def __init__(self):
        super().__init__()
        self.lecturer ='직업이 있는 강사'

    def display_info(self):
        print(self.lecturer)
        print(f'강사료 : {self.charge * 0.5}원 \n')

if __name__ == "__main__" :

    lect_1=Lecturer()
    lect_1.display_info()
    lect = GeneralLecturer()
    lect.display_info()

    lect01=LecturerAtGS()
    lect01.display_info()

    lect02 = LectureNight()
    lect02.display_info()

    lect03 = LectureWiithWork()
    lect03.display_info()


TypeError: Can't instantiate abstract class Lecturer without an implementation for abstract method 'display_info'

In [33]:
from abc import ABC, abstractmethod

class Lecture(ABC):
    def __init__(self):
        self.lecturer = "일반강사"
        self.charge = 9000

    @abstractmethod
    def display_info(self):
        pass

class LectureNight(Lecture):
    def __init__(self):
        super().__init__()
        self.lecturer = '야간강사'
        self.charge_multiplier = 1.5

    def display_info(self):
        print(self.lecturer)
        print(f'강사료: {self.charge * self.charge_multiplier}원\n')

class LecturerAtGS(Lecture):
    def __init__(self):
        super().__init__()
        self.lecturer = '대학원 강사'
        self.charge_multiplier = 2

    def display_info(self):
        print(self.lecturer)
        print(f'강사료: {self.charge * self.charge_multiplier}원\n')

class LectureWithWork(Lecture):
    def __init__(self):
        super().__init__()
        self.lecturer = '직업이 있는 강사'
        self.charge_multiplier = 0.5

    def display_info(self):
        print(self.lecturer)
        print(f'일일 주차비: {self.charge * self.charge_multiplier}원\n')

if __name__ == "__main__":
    lect = Lecture()  # 이 줄은 오류를 발생시킵니다. 추상 클래스는 객체를 생성할 수 없습니다.
    lect01 = LectureNight()
    lect01.display_info()

    lect02 = LecturerAtGS()
    lect02.display_info()

    lect03 = LectureWithWork()
    lect03.display_info()


TypeError: Can't instantiate abstract class Lecture without an implementation for abstract method 'display_info'

In [45]:
class MultiFunctionDevice :
    def print(self):
        pass
    
    def scan (self):
        pass

    def fax (self):
        pass

class SmartPrinter( MultiFunctionDevice):
    def print(self):
        print('문서 인쇄 중 ...')

    def scan(self):
        print('문서 스캔 중...')

    def fax (self):
        print('팩스 전송 중...')


class BasicPrinter(MultiFunctionDevice):
    def print(self):
        print('문서 인쇄 중...')
    
    def scan(self):
        return print(NotImplementedError('스캔기능 미지원'))
    
    def fax(self):
        raise NotImplementedError('팩스기능 미지원')
    


if __name__ == "__main__" :
    printer = SmartPrinter()
    printer.print()
    printer.scan()
    printer.fax()
    print()
    basic_printer = BasicPrinter()
    basic_printer.print()
    basic_printer.scan()
    basic_printer.fax()



문서 인쇄 중 ...
문서 스캔 중...
팩스 전송 중...

문서 인쇄 중...
스캔기능 미지원


NotImplementedError: 팩스기능 미지원

In [50]:
class Printer:
    def print(self):
        pass
    
class Scanner_Fax:
    def scan (self):
        pass

    def fax (self):
        pass

class SmartPrinter(Printer,Scanner_Fax):
    def print(self):
        print('문서 인쇄 중 ...')

    def scan(self):
        print('문서 스캔 중...')

    def fax (self):
        print('팩스 전송 중...')


class BasicPrinter(Printer):
    def print(self):
        print('문서 인쇄 중...')
    

    


if __name__ == "__main__" :
    printer = SmartPrinter()
    printer.print()
    printer.scan()
    printer.fax()
    print()
    basic_printer = BasicPrinter()
    basic_printer.print()
    basic_printer.scan()
    basic_printer.fax()



문서 인쇄 중 ...
문서 스캔 중...
팩스 전송 중...

문서 인쇄 중...


AttributeError: 'BasicPrinter' object has no attribute 'scan'

In [51]:
l=[10,20,30]
l_iter= iter(l)
l_iter

In [52]:
n=100
n_iter = iter(n)

TypeError: 'int' object is not iterable

In [54]:
try:
    l=[10,20,30]
    iterator = iter (l)
except TypeError:
    print('list는 iterable 객체가 아닙니다.')
else:
    print('list는 iterable한 객체입니다.')

list는 iterable한 객체입니다.


In [62]:
lst =[10,20,30]
l_iter= iter(lst)
type(l_iter)
next(l_iter)
l_iter.__next__()





20

In [64]:
class OddCounter:

    def __init__(self, n=1):
        self.n=n

    def __iter__(self):
        return self
    
    def __next__(self):
        t=self.n
        self.n +=2
        return t
    
my_counter = OddCounter()
print(next(my_counter))
print(my_counter.__next__())
print(my_counter.__next__())
print(my_counter.__next__())


1
3
5
7


In [66]:
ages = [34,39,20,18,13,54]
print('성년리스트:',[x for x in ages if x >= 19])

adult_ages= list(filter(lambda x :x >=19, ages))
print('성년리스트:',adult_ages)

성년리스트: [34, 39, 20, 54]
성년리스트: [34, 39, 20, 54]


In [1]:
my_generator= (x for x in range(1,4))
for n in my_generator:
        print(n)

1
2
3


In [2]:
type(my_generator)

generator

In [3]:
def create_number():
    numbers = []
    for i in range(1,11):
        numbers.append(i)
    return numbers

In [7]:
for number in create_number():
    print(number, end = ' ')
print(create_number())


1 2 3 4 5 6 7 8 9 10 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
import numpy as np

a= np.array ([[1,2,3],[4,5,6],[7,8,9]])
b= np.array([[2,2,2],
             [2,2,2],
             [2,2,2]])
print('a',a)
print('b',b)

a.max()
a.itemsize

a [[1 2 3]
 [4 5 6]
 [7 8 9]]
b [[2 2 2]
 [2 2 2]
 [2 2 2]]


8

In [16]:
import numpy as np
c=np.random.randint(0,99,10)

print(c.max())
print(c.min())
print(c.mean())


c=np.append(a,b)
print(c)

90
9
55.3
[56  0 43 81 84 15 78 75 64 60 42 21 93 49 81  4 45 42 46 63]


In [17]:
import numpy as np

# 3x3 0으로 초기화된 행렬
zero_matrix = np.zeros((3, 3))
print("0으로 초기화된 행렬:")
print(zero_matrix)

# 3x3 단위 행렬
identity_matrix = np.eye(3)
print("\n단위 행렬:")
print(identity_matrix)



0으로 초기화된 행렬:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

단위 행렬:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.full((2,3),100)

array([[100, 100, 100],
       [100, 100, 100]])

In [ ]:
np.eye(3) #단위 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.arange(0,10,2)
np.arange(0,10)
np.arange(0.0,1.0,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])